### ISSUE TITLE
What about using libyui? TUI+GUI support in one!

### ISSUE THREAD

**Issue by timofonic** [DanielBatteryStapler/PolishCalculator#1]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by DanielBatteryStapler** [comment]
While your suggestion is nice, I see no way adding a gui to this calculator would improve it in any way.
If I did add a gtk or qt based graphical system, it would work the exact same way as it does in the console. The only difference being it now has a bunch of unnecessary overhead, which a normal console does not have. I, personally, cannot see a better system for a calculator interface that isn't just typing in expressions and being given answers. Adding theming engines and graphical widgets to this would just over complicate the entire system, and, more importantly, is way outside of the scope of this project. Which is, by the way, to create a simple but powerful command line calculator. If I wanted to add some kind of graphing stuff, then I would move to a graphical front-end, but that is not what I want to do. I want to keep the original design intention as intact as possible.

Of course, comments are welcome!
